import os
import pandas as pd
from groq import Groq
from dotenv import load_dotenv

class HRRecommendationEngine:
    """
    a modular recommendation engine utilizing the groqcloud api to generate 
    prescriptive human resources analytics and intervention strategies.
    """

    def __init__(self):
        """
        initializes the groq client securely utilizing environment variables
        and loads the system prompts from the prompts directory.
        """
        #load environment variables
        load_dotenv()
        self.client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
        self.model = "llama-3.1-8b-instant"
        
        #dynamically build the path to the prompt files
        base_dir = os.path.dirname(os.path.abspath(__file__))
        
        #read retention prompt
        with open(os.path.join(base_dir, 'prompts', 'retention_prompt.txt'), 'r') as file:
            self.retention_prompt = file.read().strip()
            
        #read upskilling prompt
        with open(os.path.join(base_dir, 'prompts', 'upskilling_prompt.txt'), 'r') as file:
            self.upskilling_prompt = file.read().strip()
            
        #read workforce prompt
        with open(os.path.join(base_dir, 'prompts', 'workforce_prompt.txt'), 'r') as file:
            self.workforce_prompt = file.read().strip()

    def get_retention_strategy(self, employee_dict):
        """
        generates a personalized retention strategy for high-risk personnel.

        parameters:
        employee_dict (dict): a dictionary containing employee behavioral metrics.

        returns:
        str: an actionable retention plan generated by the large language model.
        """
        #inject variables into the text template
        prompt_content = self.retention_prompt.format(
            employee_id=employee_dict.get('Employee_ID'),
            department=employee_dict.get('Department'),
            attrition_prob=employee_dict.get('Attrition_Probability', 0) * 100,
            kpi_score=employee_dict.get('Forecasted_KPI_Score'),
            satisfaction=employee_dict.get('Satisfaction_Score'),
            compa_ratio=employee_dict.get('Compa_Ratio', 0),
            overtime=employee_dict.get('Total_Overtime_Hours', 0),
            attendance=employee_dict.get('Attendance_Status')
        )

        try:
            response = self.client.chat.completions.create(
                messages=[
                    {
                        "role": "system",
                        "content": "You generate concise, executive-grade corporate talent strategies. Maintain an academic, professional tone devoid of conversational fillers."
                    },
                    {
                        "role": "user",
                        "content": prompt_content
                    }
                ],
                model=self.model,
                temperature=0.2,
                max_tokens=400
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"api generation failed. error context: {str(e)}"

    def get_upskilling_recommendation(self, employee_dict):
        """
        analyzes an employee's skill gaps to generate targeted training track recommendations.

        parameters:
        employee_dict (dict): a dictionary containing employee performance data.

        returns:
        str: a textual training recommendation plan generated by the large language model.
        """
        #inject variables into the text template
        prompt_content = self.upskilling_prompt.format(
            department=employee_dict.get('Department'),
            kpi_score=employee_dict.get('Forecasted_KPI_Score'),
            training_hours=employee_dict.get('Training_Hours_Completed')
        )

        try:
            response = self.client.chat.completions.create(
                messages=[
                    {
                        "role": "system",
                        "content": "You are an executive instructional designer. Provide structural, precise education pathways using formal corporate terminology."
                    },
                    {
                        "role": "user",
                        "content": prompt_content
                    }
                ],
                model=self.model,
                temperature=0.1,
                max_tokens=300
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"training api generation failed. error context: {str(e)}"

    def get_workforce_optimization(self, dept_dataframe):
        """
        accepts the aggregated departmental analytics dataframe to provide resource redistribution strategies.

        parameters:
        dept_dataframe (pd.DataFrame): the aggregated department health dataframe.

        returns:
        str: a macroscopic organizational workforce report.
        """
        #convert dataframe to string and inject into template
        dataframe_string = dept_dataframe.to_string(index=False)
        prompt_content = self.workforce_prompt.format(data_matrix=dataframe_string)

        try:
            response = self.client.chat.completions.create(
                messages=[
                    {
                        "role": "system",
                        "content": "You generate highly analytical organizational development briefs. Rely strictly on statistical anomalies within the text matrix."
                    },
                    {
                        "role": "user",
                        "content": prompt_content
                    }
                ],
                model=self.model,
                temperature=0.2,
                max_tokens=500
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"workforce optimization generation failed. error context: {str(e)}"